# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Taimoor Ahmed Khan
description: "Hi, I'm Taimoor – a dynamic Data Scientist and Business Intelligence professional turning complex data into actionable insights. My portfolio showcases innovative projects where I focus on business growth, operational efficiency and drive revenue growth. Visit my Github, LinkedIn, or download my resume using the links below to learn more!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Los Angeles, USA"
resume_url: /docs/Taimoor_Ahmed_Khan_Resume_January-2025.doc
avatar_image: /img/Cropped-tk.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/taimoor-khan-analyzewithtk/" # Add your linkedln handle
github: "https://github.com/teekay094"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



